development:
  forest_env_secret: 217f4cd1bb4cfe100a4721f118c8de25f86ab0a02ad68098c3873e7215eeee49
  forest_auth_secret: wMfpRJ3rBnIh2krto3SOZQ
  forest_application_url: http://localhost:3000
staging:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET_STAGING"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET_STAGING"] %>
  forest_application_url: <%= ENV["FOREST_APPLICATION_URL_STAGING"] %>
production:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
  forest_application_url: <%= ENV["FOREST_APPLICATION_URL"] %>
